# This file describes a Fastly Compute package. To learn more visit:
# https://www.fastly.com/documentation/reference/compute/fastly-toml

authors = [""]
cloned_from = "https://github.com/fastly/compute-starter-kit-javascript-default"
description = "Fastly compute service to fetch config from github behind {service_name}.edgecompute.app domain"
language = "javascript"
manifest_version = 3
name = "fetch-config.edgecompute.app"
service_id = ""

[local_server]

  [local_server.backends]

    [local_server.backends.github]
      url = "https://raw.githubusercontent.com/"

[scripts]
  build = "npm run build"
  post_init = "npm install"
